### ISSUE TITLE
[BUG]: Resupplier not there?

### ISSUE THREAD

**Issue by Kibasmoothie** [YimMenu-Lua/Samurais-Scripts#18]
### Describe The Bug

I might just be ultra dumb and i also dont wanna bother BUT i can´t seem to find the Resupplier in the script at all. In the lua file i can find it but inside the game? Not at all. No clue i might be missing something

### Steps To Reproduce

I HAVE NO IDEA lmao

### Log

No log

**Comment by Kibasmoothie** [comment]
ahhhh 1 sec i gotta test

**Comment by Kibasmoothie** [comment]
Yep found it. Not compatible with Extras Addon. If you use Extras addon it will get merged into the UI of it somewhere. This happened with other scripts before that they got merged into Extras UI

**Comment by xesdoog** [comment]
> Yep found it. Not compatible with Extras Addon. If you use Extras addon it will get merged into the UI of it somewhere. This happened with other scripts before that they got merged into Extras UI

It wasn't merged into Extras. This happens when two or more tabs share the same name, only one will be created. This also happens if you try to create a Lua script that has a tab named `"Self"`, it will not be created because there already is a tab with the same name (YimMenu's **Self** tab).
I'll fix this when I get home. I just need to change the name "Business Manager" to something else. 
Thanks for letting me know about it

**Comment by Kibasmoothie** [comment]
Yeah yeah ik it wasn´t merged. Im not a Github fanatic and therefore use merge a bit differently. I meant merged like it was forced into the Tab cause the tab is named the same. Not something big as i know where its located but ty anyways

**Comment by xesdoog** [comment]
> I meant merged like it was forced into the Tab cause the tab is named the same.

That's what I meant too, it wasn't forced into Extras tab but it wasn't created at all.
Anyway, it should be fixed now and if you face any similar issues, don't hesitate to report them.

Have fun!
